#include "RetroEngine.hpp"

#if RETRO_USE_NATIVE_OBJECTS

#include "NativeScriptOps.hpp"
#include "NativeObjectsGen.hpp" // all transpiled objects
#include "PlayerConstants.hpp"
#include "RemasterMenu.hpp"     // remastered menus replace some stock screens

// -----------------------------------------------------------------------------
//  Registration table — generated by tools/batch_transpile.py --emit. Keyed by
//  script path (see NativeObjectHooks::scriptPath).
// -----------------------------------------------------------------------------
using namespace Native;
static const NativeObjectHooks nativeRegistry[] = {
#include "NativeRegistryGen.inl"
};
static const int nativeRegistryCount = sizeof(nativeRegistry) / sizeof(nativeRegistry[0]);

// Per-type script paths for the loading stage (filled by LoadStageFiles).
char objectScriptPaths[OBJECT_COUNT][0x40];

// Resolved per-type dispatch, rebuilt each stage. Index == live object type ID.
static NativeObjectHooks nativeObjectList[OBJECT_COUNT];

// Case-insensitive, slash-insensitive script path compare ("R1\\Boss.txt" ==
// "r1/boss.txt"). Mirrors StrComp's case folding.
static bool ScriptPathComp(const char *a, const char *b)
{
    while (*a || *b) {
        char ca = *a, cb = *b;
        if (ca == '\\') ca = '/';
        if (cb == '\\') cb = '/';
        if (ca >= 'A' && ca <= 'Z') ca += ' ';
        if (cb >= 'A' && cb <= 'Z') cb += ' ';
        if (ca != cb)
            return false;
        ++a;
        ++b;
    }
    return true;
}

// Objects kept on the interpreter until individually verified against the live
// game (the migration is incremental & hybrid by design). The Player is the
// highest-risk transliteration — its ObjectMain drives control/physics/every
// state, and the interpreted version is known-good — so it stays interpreted
// until validated frame-by-frame. Its cross-object functions (Player_Hit,
// Player_Kill, Player_State_*, ...) then also fall back to the interpreter,
// keeping behaviour consistent.
static const char *nativeExcludePaths[] = {
    // The Player now binds natively (its state machine dispatches through the
    // native funcs[] table via CallPlayerFunc, no interpreter). Nothing excluded;
    // a never-matching sentinel keeps the array non-empty.
    "///__none__",
};
static const int nativeExcludeCount = sizeof(nativeExcludePaths) / sizeof(nativeExcludePaths[0]);

static bool IsNativeExcluded(const char *scriptPath)
{
    for (int i = 0; i < nativeExcludeCount; ++i) {
        if (ScriptPathComp(scriptPath, nativeExcludePaths[i]))
            return true;
    }
    return false;
}

void InitNativeObjects()
{
    memset(nativeObjectList, 0, sizeof(nativeObjectList));
    ClearActiveFunctions();

    int bound = 0;
    for (int id = 0; id < OBJECT_COUNT; ++id) {
        if (!objectScriptPaths[id][0])
            continue;
        if (IsNativeExcluded(objectScriptPaths[id]))
            continue; // keep on the interpreter
        for (int r = 0; r < nativeRegistryCount; ++r) {
            if (ScriptPathComp(objectScriptPaths[id], nativeRegistry[r].scriptPath)) {
                nativeObjectList[id] = nativeRegistry[r];
                ++bound;
                break;
            }
        }
    }

    // Active cross-object functions: bound objects only, ascending type order —
    // later definitions win on duplicate names (text-compiler semantics).
    for (int id = 0; id < OBJECT_COUNT; ++id) {
        if (nativeObjectList[id].funcs)
            AddActiveFunctions(nativeObjectList[id].funcs, nativeObjectList[id].funcCount);
    }

    // Report every object that has a script path but did NOT bind natively — the
    // only things still needing the interpreter. Goal for full RetroScript removal
    // is zero of these across every scene.
    int unbound = 0;
    for (int id = 0; id < OBJECT_COUNT; ++id) {
        if (objectScriptPaths[id][0] && !nativeObjectList[id].scriptPath && !IsNativeExcluded(objectScriptPaths[id])) {
            PrintLog("NATIVE-UNBOUND type %d: %s", id, objectScriptPaths[id]);
            ++unbound;
        }
    }
    PrintLog("Native objects bound: %d, UNBOUND: %d", bound, unbound);
}

// Does this type have a native implementation for the given sub? Lets the engine
// run native objects even when no bytecode is loaded (the execution gates check
// scriptCode[...] > 0, which is empty once RetroScript is gone).
bool NativeObjectHasSub(int type, byte scriptSub)
{
    if (type <= 0 || type >= OBJECT_COUNT)
        return false;
    const NativeObjectHooks &h = nativeObjectList[type];
    switch (scriptSub) {
        case SUB_MAIN: return h.subMain != nullptr;
        case SUB_PLAYERINTERACTION: return h.subPlayerInteraction != nullptr;
        case SUB_DRAW: return h.subDraw != nullptr;
        case SUB_SETUP: return h.subSetup != nullptr;
        default: return false;
    }
}

// When set, the ProcessScript hook is suppressed so native code can invoke a
// still-interpreted script function (via CallScriptFunction) without the native
// player re-dispatching into itself.
static bool s_nativeHookBypass = false;

bool ProcessNativeObject(int type, byte scriptSub)
{
    if (s_nativeHookBypass)
        return false;
    if (type <= 0 || type >= OBJECT_COUNT)
        return false;

    // Remastered menus fully replace the stock menu screens, so while one is up
    // we drop the original screen's low-res rendering entirely (its logic still
    // runs). This is what used to bleed through during menu transitions.
    if (scriptSub == SUB_DRAW && RemasterMenu::SuppressStockMenuDraw(type))
        return true;

    const NativeObjectHooks &h = nativeObjectList[type];
    NativeObjectSub sub        = nullptr;
    switch (scriptSub) {
        case SUB_MAIN: sub = h.subMain; break;
        case SUB_PLAYERINTERACTION: sub = h.subPlayerInteraction; break;
        case SUB_DRAW: sub = h.subDraw; break;
        case SUB_SETUP: sub = h.subSetup; break;
        default: break;
    }

    if (!sub)
        return false; // not migrated for this sub -> let the interpreter run it

    // publish the sub context so CallScriptFunction* calls made from native
    // code inherit it, exactly like the interpreter's function calls
    byte prevSub          = Native::scriptSub;
    Native::scriptSub     = scriptSub;
    sub();
    Native::scriptSub = prevSub;
    return true;
}

// =============================================================================
//  Script-API bridge implementations
// =============================================================================
namespace Native
{
int TypeNameID(const char *name)
{
    // Strip spaces from the query to match typeNames[] (SetObjectTypeName strips them).
    char stripped[0x40];
    int s = 0;
    for (int i = 0; name[i] && s < 0x3F; ++i) {
        if (name[i] != ' ')
            stripped[s++] = name[i];
    }
    stripped[s] = 0;

    for (int id = 0; id < OBJECT_COUNT; ++id) {
        if (StrComp(typeNames[id], stripped))
            return id;
    }
    return 0; // blank object
}

void CallScriptFunction(int functionID, byte scriptSub)
{
    // ScriptFuncID returns -1 for a name that isn't loaded; guard it (a script
    // that stored an unresolved function ID and calls it is a no-op, same as an
    // empty script function).
    if (functionID < 0 || functionID >= scriptFunctionCount)
        return;
    bool prev          = s_nativeHookBypass;
    s_nativeHookBypass = true;
    ProcessScript(scriptFunctionList[functionID].ptr.scriptCodePtr, scriptFunctionList[functionID].ptr.jumpTablePtr, scriptSub);
    s_nativeHookBypass = prev;
}

int CreateTempObject(int type, int propertyValue, int xpos, int ypos)
{
    // Advance the temp-slot ring to the next free slot (same as FUNC_CREATETEMPOBJECT).
    if (objectEntityList[scriptEng.arrayPosition[2]].type > 0 && ++scriptEng.arrayPosition[2] == ENTITY_COUNT)
        scriptEng.arrayPosition[2] = TEMPENTITY_START;

    Entity *temp         = &objectEntityList[scriptEng.arrayPosition[2]];
    temp->type           = type;
    temp->propertyValue  = propertyValue;
    temp->XPos           = xpos;
    temp->YPos           = ypos;
    temp->direction      = FLIP_NONE;
    temp->frame          = 0;
    temp->priority       = PRIORITY_ACTIVE;
    temp->rotation       = 0;
    temp->state          = 0;
    temp->drawOrder      = 3;
    temp->scale          = 512;
    temp->inkEffect      = INK_NONE;
    temp->alpha          = 0;
    temp->animation      = 0;
    temp->prevAnimation  = 0;
    temp->animationSpeed = 0;
    temp->animationTimer = 0;
    for (int i = 0; i < 8; ++i) temp->values[i] = 0;
    return scriptEng.arrayPosition[2];
}

void ResetObjectEntity(int slot, int type, int propertyValue, int xpos, int ypos)
{
    Entity *newEnt        = &objectEntityList[slot];
    newEnt->type          = type;
    newEnt->propertyValue = propertyValue;
    newEnt->XPos          = xpos;
    newEnt->YPos          = ypos;
    newEnt->direction     = FLIP_NONE;
    newEnt->frame         = 0;
    newEnt->priority      = PRIORITY_BOUNDS;
    newEnt->rotation      = 0;
    newEnt->state         = 0;
    newEnt->drawOrder     = 3;
    newEnt->scale         = 0x200;
    newEnt->inkEffect     = INK_NONE;
    for (int i = 0; i < 8; ++i) newEnt->values[i] = 0;
}

void PlayerObjectCollision(int type, int left, int top, int right, int bottom)
{
    Entity *entity           = Self();
    ObjectScript *scriptInfo = &objectScriptList[entity->type];

    // NOTE: this is a faithful copy of FUNC_PLAYEROBJECTCOLLISION. The C_BOX2 /
    // C_PLATFORM behaviour depends on whether the loaded bytecode is the mobile
    // build (scriptInfo->mobile). On PC/standalone bytecode C_PLATFORM is a
    // no-op and C_BOX2 becomes PlatformCollision, so we preserve that quirk.
    switch (type) {
        default: break;
        case C_TOUCH: {
            int ix = entity->XPos >> 16;
            int iy = entity->YPos >> 16;
            TouchCollision(ix + left, iy + top, ix + right, iy + bottom);
            break;
        }
        case C_BOX:
            BoxCollision(entity->XPos + (left << 16), entity->YPos + (top << 16), entity->XPos + (right << 16),
                         entity->YPos + (bottom << 16));
            break;
        case C_BOX2:
            if (!scriptInfo->mobile)
                PlatformCollision(entity->XPos + (left << 16), entity->YPos + (top << 16), entity->XPos + (right << 16),
                                  entity->YPos + (bottom << 16));
            else
                BoxCollision2(entity->XPos + (left << 16), entity->YPos + (top << 16), entity->XPos + (right << 16),
                              entity->YPos + (bottom << 16));
            break;
        case C_PLATFORM:
            if (scriptInfo->mobile)
                PlatformCollision(entity->XPos + (left << 16), entity->YPos + (top << 16), entity->XPos + (right << 16),
                                  entity->YPos + (bottom << 16));
            break;
    }
}

void DrawSpriteFX_Flip(int frameID, int xpos, int ypos)
{
    Entity *entity           = Self();
    ObjectScript *scriptInfo = &objectScriptList[entity->type];
    SpriteFrame *frame       = &scriptFrames[scriptInfo->frameListOffset + frameID];

    // Exact copy of FUNC_DRAWSPRITEFX's FX_FLIP branch: pivot handling differs
    // per flip direction (mirrored sprites subtract width/height + pivot).
    int x = (xpos >> 16) - xScrollOffset;
    int y = (ypos >> 16) - yScrollOffset;
    switch (entity->direction) {
        default:
        case FLIP_NONE:
            DrawSpriteFlipped(x + frame->pivotX, y + frame->pivotY, frame->width, frame->height, frame->sprX, frame->sprY, FLIP_NONE,
                              scriptInfo->spriteSheetID);
            break;
        case FLIP_X:
            DrawSpriteFlipped(x - frame->width - frame->pivotX, y + frame->pivotY, frame->width, frame->height, frame->sprX, frame->sprY,
                              FLIP_X, scriptInfo->spriteSheetID);
            break;
        case FLIP_Y:
            DrawSpriteFlipped(x + frame->pivotX, y - frame->height - frame->pivotY, frame->width, frame->height, frame->sprX, frame->sprY,
                              FLIP_Y, scriptInfo->spriteSheetID);
            break;
        case FLIP_XY:
            DrawSpriteFlipped(x - frame->width - frame->pivotX, y - frame->height - frame->pivotY, frame->width, frame->height, frame->sprX,
                              frame->sprY, FLIP_XY, scriptInfo->spriteSheetID);
            break;
    }
}

void DrawSprite_Frame(int frameID)
{
    Entity *entity           = Self();
    ObjectScript *scriptInfo = &objectScriptList[entity->type];
    ::SpriteFrame *f         = &scriptFrames[scriptInfo->frameListOffset + frameID];
    DrawSprite((entity->XPos >> 16) - xScrollOffset + f->pivotX, (entity->YPos >> 16) - yScrollOffset + f->pivotY, f->width, f->height,
               f->sprX, f->sprY, scriptInfo->spriteSheetID);
}

void LoadSpriteSheet(const char *path)
{
    ObjectScript *scriptInfo  = &objectScriptList[Self()->type];
    scriptInfo->spriteSheetID = AddGraphicsFile(path);
}

void AddSpriteFrame(int pivotX, int pivotY, int width, int height, int sprX, int sprY)
{
    if (scriptFrameCount >= SPRITEFRAME_COUNT)
        return;
    ::SpriteFrame *f = &scriptFrames[scriptFrameCount++];
    f->pivotX      = pivotX;
    f->pivotY      = pivotY;
    f->width       = width;
    f->height      = height;
    f->sprX        = sprX;
    f->sprY        = sprY;
}
} // namespace Native

#endif // RETRO_USE_NATIVE_OBJECTS
